#!/usr/bin/env bash
# Shared helpers for parchment hooks.

CANVAS_STATE_DIR="${HOME}/.parchment"
CANVAS_PORT_FILE="${CANVAS_STATE_DIR}/server.port"
CANVAS_PID_FILE="${CANVAS_STATE_DIR}/server.pid"
CANVAS_TOKEN_FILE="${CANVAS_STATE_DIR}/server.token"
CANVAS_LOG_FILE="${CANVAS_STATE_DIR}/server.log"
CANVAS_DEFAULT_PORT="${CANVAS_PORT:-7800}"
CANVAS_TOKEN_HEADER="X-Canvas-Token"

canvas_token() {
  if [[ -f "${CANVAS_TOKEN_FILE}" ]]; then
    cat "${CANVAS_TOKEN_FILE}"
  fi
}

canvas_port() {
  if [[ -f "${CANVAS_PORT_FILE}" ]]; then
    cat "${CANVAS_PORT_FILE}"
  else
    echo "${CANVAS_DEFAULT_PORT}"
  fi
}

canvas_base_url() {
  echo "http://localhost:$(canvas_port)"
}

# Emit a stable launcher at ~/.parchment/statusline.sh that execs the current
# plugin's statusline. Users point settings.json at this fixed path instead of
# a versioned plugin path (~/.claude/plugins/cache/.../<version>/scripts/...)
# that dangles on every plugin update. Rewritten each SessionStart so it always
# targets the installed version; if the target ever goes missing it degrades to
# a one-line notice instead of a blank statusline.
canvas_write_statusline_launcher() {
  local target="${CLAUDE_PLUGIN_ROOT}/scripts/statusline.sh"
  local launcher="${CANVAS_STATE_DIR}/statusline.sh"
  cat > "${launcher}" <<LAUNCHER
#!/usr/bin/env bash
# Auto-generated by parchment — do not edit; rewritten every session to
# track the installed plugin version. Point settings.json statusLine here:
#   "command": "bash ~/.parchment/statusline.sh"
target="${target}"
if [[ ! -f "\$target" ]]; then
  printf '◐ canvas: statusline unavailable (reinstall parchment)'
  exit 0
fi
exec bash "\$target" "\$@"
LAUNCHER
  chmod +x "${launcher}" 2>/dev/null || true
}

# Compact session url for status line. First 6 hex chars of the session id.
canvas_session_short_url() {
  local session_id="$1"
  local hex
  hex="$(printf '%s' "${session_id}" | tr 'A-Z' 'a-z' | tr -cd '0-9a-f' | cut -c1-6)"
  if [[ -z "${hex}" ]]; then
    hex="$(printf '%s' "${session_id}" | tr -cd 'A-Za-z0-9' | cut -c1-6 | tr 'A-Z' 'a-z')"
    if [[ -z "${hex}" ]]; then hex="default"; fi
  fi
  echo "localhost:$(canvas_port)/s/${hex}"
}

canvas_session_short_href() {
  echo "http://$(canvas_session_short_url "$1")"
}

# Full session url — what the browser actually subscribes to. The /s/ redirect
# resolves to this so a click via OSC-8 always lands on the right session.
canvas_session_full_href() {
  local session_id="$1"
  local safe_id
  safe_id="$(printf '%s' "${session_id}" | sed 's/[^A-Za-z0-9._-]/_/g')"
  echo "http://localhost:$(canvas_port)/?session=${safe_id}"
}

canvas_slots_dir() {
  local session_id="$1"
  local safe_id
  safe_id="$(printf '%s' "${session_id}" | sed 's/[^A-Za-z0-9._-]/_/g')"
  echo "${CANVAS_STATE_DIR}/sessions/${safe_id}/slots"
}

# Liveness = answers /api/health AND identifies as parchment. A PID check is
# wrong twice over: stale PID files get recycled to unrelated processes, and
# a wedged daemon that still holds a PID shouldn't count as alive. The
# identity check keeps a foreign daemon on a stale port (e.g. a legacy
# clawd-canvas install) from masquerading as ours.
canvas_server_alive() {
  local health
  health="$(curl -fsS --max-time 0.5 "$(canvas_base_url)/api/health" 2>/dev/null)" || return 1
  [[ "${health}" == *'"app":"parchment"'* ]]
}

# True when the running daemon is executing code older than what's on disk (a
# plugin update or rebuild landed after it booted). server.build's mtime is the
# daemon's boot time; if any runtime source or the built bundle is newer, it's
# stale. find -newer is POSIX (macOS + Linux) — no stat-format portability shims.
# Absent marker → unknown (a pre-marker daemon) → not stale, so we never loop.
canvas_daemon_is_stale() {
  local marker="${CANVAS_STATE_DIR}/server.build"
  [[ -f "${marker}" ]] || return 1
  [[ -n "${CLAUDE_PLUGIN_ROOT:-}" ]] || return 1
  local newer
  newer="$(find \
    "${CLAUDE_PLUGIN_ROOT}/src/daemon" \
    "${CLAUDE_PLUGIN_ROOT}/src/shared" \
    "${CLAUDE_PLUGIN_ROOT}/dist/browser/index.html" \
    -newer "${marker}" 2>/dev/null | head -n1)"
  [[ -n "${newer}" ]]
}

# Stop the running daemon and wait for the port to free up. SIGTERM makes it
# exit cleanly (it clears its own state files on exit), so the replacement binds
# the same port instead of falling back to 7801.
canvas_stop_daemon() {
  [[ -f "${CANVAS_PID_FILE}" ]] || return 0
  local pid
  pid="$(cat "${CANVAS_PID_FILE}" 2>/dev/null)"
  [[ -n "${pid}" ]] || return 0
  kill "${pid}" 2>/dev/null || true
  local attempts=20
  while (( attempts > 0 )) && canvas_server_alive; do
    sleep 0.1
    attempts=$((attempts - 1))
  done
}

# Tell the daemon where this session's transcript JSONL lives so it can
# stream the conversation to the canvas. Fire-and-forget: transcript display
# is never worth blocking a prompt over.
canvas_register_transcript() {
  local session_id="$1"
  local transcript_path="$2"
  if [[ -z "${transcript_path}" || "${transcript_path}" == "null" ]]; then return 0; fi
  local safe_id
  safe_id="$(printf '%s' "${session_id}" | sed 's/[^A-Za-z0-9._-]/_/g')"
  ( curl -fsS --max-time 1 \
      -X POST "$(canvas_base_url)/api/sessions/${safe_id}/transcript" \
      -H "${CANVAS_TOKEN_HEADER}: $(canvas_token)" \
      -H "Content-Type: application/json" \
      -d "{\"path\": \"${transcript_path}\"}" >/dev/null 2>&1 || true ) &
  disown $! 2>/dev/null || true
}

# Tell the daemon which session is now in the foreground, and where it lives.
# The daemon resolves "the active claude session" for MCP calls by most-recent
# activity within a cwd, so a session started by /clear must announce its cwd
# here or it loses that pick to the session it replaced. Token-bearing (POST),
# and unconditional — it does not depend on a transcript path being present.
canvas_activate_session() {
  local session_id="$1"
  local cwd="$2"
  local safe_id
  safe_id="$(printf '%s' "${session_id}" | sed 's/[^A-Za-z0-9._-]/_/g')"
  local payload
  if command -v jq >/dev/null 2>&1; then
    payload="$(jq -n --arg cwd "${cwd}" '{cwd: $cwd}')"
  else
    payload="{\"cwd\": \"${cwd}\"}"
  fi
  curl -fsS --max-time 2 \
    -X POST "$(canvas_base_url)/api/sessions/${safe_id}/activate" \
    -H "${CANVAS_TOKEN_HEADER}: $(canvas_token)" \
    -H "Content-Type: application/json" \
    -d "${payload}" >/dev/null 2>&1 || true
}

canvas_session_id_from() {
  local json="$1"
  local parsed
  if command -v jq >/dev/null 2>&1; then
    parsed="$(printf '%s' "${json}" | jq -r '.session_id // "default"')"
  else
    parsed="$(printf '%s' "${json}" | sed -n 's/.*"session_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
  fi
  printf '%s' "${parsed:-default}"
}

canvas_set_status() {
  local session_id="$1"
  local status="$2"
  local safe_id
  safe_id="$(printf '%s' "${session_id}" | sed 's/[^A-Za-z0-9._-]/_/g')"
  ( curl -fsS --max-time 1 \
      -X POST "$(canvas_base_url)/api/sessions/${safe_id}/status" \
      -H "${CANVAS_TOKEN_HEADER}: $(canvas_token)" \
      -H "Content-Type: application/json" \
      -d "{\"status\": \"${status}\"}" >/dev/null 2>&1 || true ) &
  disown $! 2>/dev/null || true
}

canvas_wait_for_health() {
  local attempts=20
  while (( attempts > 0 )); do
    if canvas_server_alive; then
      return 0
    fi
    sleep 0.2
    attempts=$((attempts - 1))
  done
  return 1
}
